SET MODE PostgreSQL;

CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email varchar(100) UNIQUE NOT NULL,
    user_login varchar(100) UNIQUE NOT NULL,
    user_name varchar(100) NOT NULL,
    user_birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS MPA (
    mpa_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS friendships (
    friendship_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id int REFERENCES users (user_id),
    friend_id int REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS films (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(255) NOT NULL,
    film_description varchar(255) NOT NULL,
    film_releaseDate date NOT NULL ,
    film_duration int CHECK (film_duration > 0) NOT NULL,
    mpa_id int REFERENCES MPA (mpa_id)
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
    film_id int REFERENCES films (film_id),
    genre_id int REFERENCES genres (genre_id),
    CONSTRAINT fg_pk PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
    user_id int REFERENCES users (user_id),
    film_id int REFERENCES films (film_id),
    CONSTRAINT likes_pk PRIMARY KEY (user_id, film_id)
);
